[accounts.gmail-1]
default = true

imap.mailbox = "INBOX"
imap.server = "imaps://imap.gmail.com:993"
imap.sasl.plain.authcid = "arashahady2001@gmail.com"
imap.sasl.plain.passwd.command = "pass Gmail/arashahady2001@gmail.com | tail -n 1"
imap.hook.on-message-added.notify.body = "From: $sender\nSubject: $subject"
imap.hook.on-message-added.notify.summary = "New mail"
imap.watch.poll.interval = 1

[accounts.gmail-2]
imap.mailbox = "INBOX"
imap.server = "imaps://imap.gmail.com:993"
imap.sasl.plain.authcid = "ara.ahady@gmail.com"
imap.sasl.plain.passwd.command = "pass Gmail/ara.ahady@gmail.com | tail -n 1"
imap.hook.on-message-added.notify.body = "From: $sender\n$subject"
imap.hook.on-message-added.notify.summary = "New mail"
imap.watch.poll.interval = 1
