local config = {
    undercurl = false,
    underline = false,
    bold = false,
    italic = {
        strings = false,
        comments = true,
        operators = false,
        folds = false,
        emphasis = false,
    },
    strikethrough = false,
    invert_selection = false,
    invert_signs = false,
    invert_tabline = false,
    invert_intend_guides = false,
    inverse = false,
    dim_inactive = false,
    transparent_mode = true,
}

local colors = {
    bg0 = "#242424",
    bg1 = "#3c3836",
    bg2 = "#7c6f64",
    bg3 = "#665c54",
    bg4 = "#7c6f64",
    fg0 = "#fbf1c7",
    fg1 = "#ebdbb2",
    fg2 = "#d5c4a1",
    fg3 = "#bdae93",
    fg4 = "#a89984",
    red = "#fb4934",
    green = "#9dc365",
    yellow = "#fabd2f",
    blue = "#83a598",
    purple = "#d3869b",
    aqua = "#8ec07c",
    orange = "#fe8019",
    neutral_red = "#cc241d",
    neutral_green = "#9dc365",
    neutral_yellow = "#d79921",
    neutral_blue = "#458588",
    neutral_purple = "#b16286",
    neutral_aqua = "#689d6a",
    neutral_orange = "#d65d0e",
    dark_red = "#722529",
    dark_green = "#62693e",
    dark_aqua_hard = "#3e4934",
    dark_aqua = "#49503b",
    dark_aqua_soft = "#525742",
    gray = "#928374",
}

local groups = {
    GruvboxFg0 = { fg = colors.fg0 },
    GruvboxFg1 = { fg = colors.fg1 },
    GruvboxFg2 = { fg = colors.fg2 },
    GruvboxFg3 = { fg = colors.fg3 },
    GruvboxFg4 = { fg = colors.fg4 },
    GruvboxGray = { fg = colors.gray },
    GruvboxBg0 = { fg = colors.bg0 },
    GruvboxBg1 = { fg = colors.bg1 },
    GruvboxBg2 = { fg = colors.bg2 },
    GruvboxBg3 = { fg = colors.bg3 },
    GruvboxBg4 = { fg = colors.bg4 },
    GruvboxRed = { fg = colors.red },
    GruvboxRedBold = { fg = colors.red, bold = config.bold },
    GruvboxGreen = { fg = colors.green },
    GruvboxGreenBold = { fg = colors.green, bold = config.bold },
    GruvboxYellow = { fg = colors.yellow },
    GruvboxYellowBold = { fg = colors.yellow, bold = config.bold },
    GruvboxBlue = { fg = colors.blue },
    GruvboxBlueBold = { fg = colors.blue, bold = config.bold },
    GruvboxPurple = { fg = colors.purple },
    GruvboxPurpleBold = { fg = colors.purple, bold = config.bold },
    GruvboxAqua = { fg = colors.aqua },
    GruvboxAquaBold = { fg = colors.aqua, bold = config.bold },
    GruvboxOrange = { fg = colors.orange },
    GruvboxOrangeBold = { fg = colors.orange, bold = config.bold },
    GruvboxRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
        or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
        or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
        or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
        or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
        or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
        or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
        or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    GruvboxRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    GruvboxGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    GruvboxYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    GruvboxBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    GruvboxPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    GruvboxAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    GruvboxOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },

    GrugFarResultsMatch = { link = "Search" },
    GrugFarResultsHeader = { default = true, link = "GruvboxGreen" },

    debugPC = { bg = colors.blue, fg = colors.bg0 },
    debugBreakpoint = { link = "GruvboxRedSign" },
    DapBreakpoint = { fg = colors.red },
    DapStopped = { fg = colors.green },
    DapUIBreakpointsCurrentLine = { link = "GruvboxYellow" },
    DapUIBreakpointsDisabledLine = { link = "GruvboxGray" },
    DapUIBreakpointsInfo = { link = "GruvboxAqua" },
    DapUIBreakpointsLine = { link = "GruvboxYellow" },
    DapUIBreakpointsPath = { link = "GruvboxBlue" },
    DapUICurrentFrameName = { link = "GruvboxPurple" },
    DapUIDecoration = { link = "GruvboxPurple" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "GruvboxAqua" },
    DapUILineNumber = { link = "GruvboxYellow" },
    DapUIModifiedValue = { link = "GruvboxRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "GruvboxBlue" },
    DapUISource = { link = "GruvboxFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "GruvboxBlue" },
    DapUIThread = { link = "GruvboxBlue" },
    DapUIType = { link = "GruvboxOrange" },
    DapUIUnavailable = { link = "GruvboxGray" },
    DapUIWatchesEmpty = { link = "GruvboxGray" },
    DapUIWatchesError = { link = "GruvboxRed" },
    DapUIWatchesValue = { link = "GruvboxYellow" },
    DapUIWinSelect = { link = "GruvboxYellow" },

    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg0 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    TermCursor = { bg = "#9CD365" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "GruvboxBg4" },
    SpecialKey = { link = "GruvboxBg4" },
    SpecialChar = { link = "GruvboxRed" },
    Visual = { bg = "#3F3F3F", reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.bg0, bg = colors.blue, reverse = config.inverse },
    IncSearch = { fg = colors.bg0, bg = "#D8A657", reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "None" },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { bg = colors.bg0, reverse = config.inverse },
    StatusLineNC = { fg = "#E6DBAF", bg = colors.bg0, reverse = config.inverse },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "None" },
    Title = { link = "GruvboxGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "GruvboxYellowBold" },
    ModeMsg = { link = "GruvboxYellowBold" },
    Question = { link = "GruvboxOrangeBold" },
    WarningMsg = { link = "GruvboxRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { link = "GruvboxBlue" },
    FoldColumn = { link = "GruvboxAqua" },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "GruvboxOrange" },
    Comment = { fg = colors.gray, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = false },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "GruvboxRed" },
    Conditional = { link = "GruvboxRed" },
    Repeat = { link = "GruvboxRed" },
    Label = { link = "GruvboxRed" },
    Exception = { link = "GruvboxRed" },
    Operator = { fg = colors.orange, italic = config.italic.operators },
    Keyword = { link = "GruvboxRed" },
    Identifier = { link = "GruvboxBlue" },
    Function = { link = "GruvboxGreenBold" },
    PreProc = { link = "GruvboxAqua" },
    Include = { link = "GruvboxRed" },
    Define = { link = "GruvboxAqua" },
    Macro = { link = "GruvboxAqua" },
    PreCondit = { link = "GruvboxAqua" },
    Constant = { link = "GruvboxPurple" },
    Character = { link = "GruvboxPurple" },
    String = { fg = colors.green, italic = config.italic.strings },
    Boolean = { link = "GruvboxPurple" },
    Number = { link = "GruvboxPurple" },
    Float = { link = "GruvboxPurple" },
    FloatBorder = { link = "GruvboxBlue" },
    Type = { link = "GruvboxYellow" },
    StorageClass = { link = "GruvboxOrange" },
    Structure = { link = "GruvboxAqua" },
    Typedef = { link = "GruvboxYellow" },
    Pmenu = { link = "None" },
    PmenuSel = { bg = colors.bg2, fg = "#E6DBAF" },
    PmenuSbar = { link = "None" },
    PmenuThumb = { link = "None" },
    DiffDelete = { bg = colors.dark_red },
    DiffAdd = { bg = colors.dark_green },
    DiffChange = { bg = colors.dark_aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "GruvboxBlueUnderline" },
    SpellBad = { link = "GruvboxRedUnderline" },
    SpellLocal = { link = "GruvboxAquaUnderline" },
    SpellRare = { link = "GruvboxPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    DiagnosticError = { link = "GruvboxRed" },
    DiagnosticSignError = { link = "GruvboxRedSign" },
    DiagnosticUnderlineError = { link = "GruvboxRedUnderline" },
    DiagnosticWarn = { link = "GruvboxYellow" },
    DiagnosticSignWarn = { link = "GruvboxYellowSign" },
    DiagnosticUnderlineWarn = { link = "GruvboxYellowUnderline" },
    DiagnosticInfo = { link = "GruvboxBlue" },
    DiagnosticSignInfo = { link = "GruvboxBlueSign" },
    DiagnosticUnderlineInfo = { link = "GruvboxBlueUnderline" },
    DiagnosticHint = { link = "GruvboxAqua" },
    DiagnosticSignHint = { link = "GruvboxAquaSign" },
    DiagnosticUnderlineHint = { link = "GruvboxAquaUnderline" },
    DiagnosticFloatingError = { link = "GruvboxRed" },
    DiagnosticFloatingWarn = { link = "GruvboxOrange" },
    DiagnosticFloatingInfo = { link = "GruvboxBlue" },
    DiagnosticFloatingHint = { link = "GruvboxAqua" },
    DiagnosticVirtualTextError = { link = "GruvboxRed" },
    DiagnosticVirtualTextWarn = { link = "GruvboxYellow" },
    DiagnosticVirtualTextInfo = { link = "GruvboxBlue" },
    DiagnosticVirtualTextHint = { link = "GruvboxAqua" },
    DiagnosticOk = { link = "GruvboxGreenSign" },
    LspReferenceRead = { link = "GruvboxYellowBold" },
    LspReferenceText = { link = "GruvboxYellowBold" },
    LspReferenceWrite = { link = "GruvboxOrangeBold" },
    LspCodeLens = { link = "GruvboxGray" },
    LspSignatureActiveParameter = { link = "Search" },

    CmpItemAbbr = { link = "GruvboxFg0" },
    CmpItemAbbrDeprecated = { link = "GruvboxFg1" },
    CmpItemAbbrMatch = { link = "GruvboxBlue" },
    CmpItemAbbrMatchFuzzy = { link = "GruvboxBlueUnderline" },
    CmpItemMenu = { link = "GruvboxRed", reverse = true },
    CmpSelMenu = { bg = colors.bg0 },
    CmpSelBackground = { link = "Visual" },
    CmpItemKindText = { link = "StatuslineCmdLineAccent" },
    CmpItemKindVariable = { link = "StatuslineCmdLineAccent" },
    CmpItemKindMethod = { link = "GruvboxRed" },
    CmpItemKindFunction = { link = "StatuslineAccent" },
    CmpItemKindConstructor = { link = "StatuslineVisualAccent" },
    CmpItemKindUnit = { link = "StatuslineAccent" },
    CmpItemKindField = { link = "LspDiagnosticError" },
    CmpItemKindClass = { link = "StatuslineVisualAccent" },
    CmpItemKindInterface = { link = "StatuslineVisualAccent" },
    CmpItemKindModule = { link = "StatuslineInsertAccent" },
    CmpItemKindProperty = { link = "StatuslineAccent" },
    CmpItemKindValue = { link = "StatuslineCmdLineAccent" },
    CmpItemKindEnum = { link = "StatuslineVisualAccent" },
    CmpItemKindOperator = { link = "StatuslineVisualAccent" },
    CmpItemKindKeyword = { link = "StatuslineReplaceAccent" },
    CmpItemKindEvent = { link = "StatuslineReplaceAccent" },
    CmpItemKindReference = { link = "StatuslineReplaceAccent" },
    CmpItemKindColor = { link = "StatuslineReplaceAccent" },
    CmpItemKindSnippet = { link = "StatuslineInsertAccent" },
    CmpItemKindFile = { link = "StatuslineAccent" },
    CmpItemKindFolder = { link = "StatuslineAccent" },
    CmpItemKindEnumMember = { link = "GruvboxAqua" },
    CmpItemKindConstant = { link = "StatuslineCmdLineAccent" },
    CmpItemKindStruct = { link = "StatuslineVisualAccent" },
    CmpItemKindTypeParameter = { link = "StatuslineVisualAccent" },

    BlinkCmpMenuSelection = { link = "Visual" },
    BlinkCmpDocBorder = { link = "GruvboxBlue" },
    BlinkCmpMenu = { bg = colors.bg0 },
    BlinkCmpLabelMatch = { link = "GruvboxBlue" },
    BlinkCmpKind = { link = "GruvboxBlue" },
    BlinkCmpKindText = { link = "StatuslineCmdLineAccent" },
    BlinkCmpKindVariable = { link = "StatuslineCmdLineAccent" },
    BlinkCmpKindMethod = { bg = colors.red, fg = colors.bg0 },
    BlinkCmpKindFunction = { link = "StatuslineAccent" },
    BlinkCmpKindConstructor = { link = "StatuslineVisualAccent" },
    BlinkCmpKindUnit = { link = "StatuslineAccent" },
    BlinkCmpKindField = { link = "LspDiagnosticError" },
    BlinkCmpKindClass = { link = "StatuslineVisualAccent" },
    BlinkCmpKindInterface = { link = "StatuslineVisualAccent" },
    BlinkCmpKindModule = { link = "StatuslineInsertAccent" },
    BlinkCmpKindProperty = { link = "StatuslineAccent" },
    BlinkCmpKindValue = { link = "StatuslineCmdLineAccent" },
    BlinkCmpKindEnum = { link = "StatuslineVisualAccent" },
    BlinkCmpKindOperator = { link = "StatuslineVisualAccent" },
    BlinkCmpKindKeyword = { link = "StatuslineReplaceAccent" },
    BlinkCmpKindEvent = { link = "StatuslineReplaceAccent" },
    BlinkCmpKindReference = { link = "StatuslineReplaceAccent" },
    BlinkCmpKindColor = { link = "StatuslineReplaceAccent" },
    BlinkCmpKindSnippet = { link = "StatuslineInsertAccent" },
    BlinkCmpKindFile = { link = "StatuslineAccent" },
    BlinkCmpKindFolder = { link = "StatuslineAccent" },
    BlinkCmpKindEnumMember = { link = "GruvboxAqua" },
    BlinkCmpKindConstant = { link = "StatuslineCmdLineAccent" },
    BlinkCmpKindStruct = { link = "StatuslineVisualAccent" },
    BlinkCmpKindTypeParameter = { link = "StatuslineVisualAccent" },

    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "GruvboxOrange" },
    diffNewFile = { link = "GruvboxYellow" },
    diffOldFile = { link = "GruvboxOrange" },
    diffLine = { link = "GruvboxBlue" },
    diffIndexLine = { link = "diffChanged" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "GruvboxAqua" },
    LspInlayHint = { link = "comment" },
    Delimiter = { link = "GruvboxOrange" },
    zshVariableDef = { link = "GruvboxBlue" },
    zshPreProc = { link = "Comment" },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.directive.bash"] = { link = "Comment" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "GruvboxRed" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "GruvboxFg1" },
    ["@markup.strong"] = { bold = config.bold },
    ["@markup.emphasis"] = { italic = config.italic.emphasis },
    ["@markup.underline"] = { underline = config.underline },
    ["@markup.strike"] = { strikethrough = config.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "GruvboxGreen" },
    ["@markup.list.unchecked"] = { link = "GruvboxGray" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "GruvboxFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "GruvboxGreen" },
    ["@text.todo.unchecked"] = { link = "GruvboxGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@constant.bash"] = { link = "GruvboxBlue" },
    ["@function.builtin.bash"] = { link = "GruvboxRed" },
    ["@namespace"] = { link = "GruvboxRed" },
    ["@variable"] = { link = "GruvboxBlue" },
    ["@tag.xml"] = { link = "GruvboxBlue" },
    ["@tag.delimiter.xml"] = { link = "GruvboxBlue" },
    ["@module"] = { link = "GruvboxBlue" },
    ["@function.builtin.lua"] = { link = "GruvboxGreenBold" },
    ["@lsp.type.comment.lua"] = { link = "None" },

    FzfLuaBufLineNr = { link = "GruvboxBlue" },

    NvimSurroundHighlight = { bg = colors.orange, fg = colors.bg0 },

    HopNextKey = { fg = colors.bg0, bg = colors.blue },
    HopNextKey1 = { fg = colors.bg0, bg = colors.blue },
    HopNextKey2 = { fg = colors.bg0, bg = "#D8A657" },

    BqfSign = { link = "GruvboxGreen" },
    IndentLine = { link = "Comment" },
    IndentLineCurrent = { fg = colors.yellow },

    MiniHipatternsFixme = { link = "ErrorMsg" },
    MiniHipatternsTodo = { link = "Todo" },
    MiniHipatternsNote = { bg = colors.orange, fg = colors.bg0, bold = true },
    MiniHipatternsHack = { bg = colors.blue, fg = colors.bg0, bold = true },
}

local function colorscheme()
    if vim.g.colors_name then
        vim.cmd.hi("clear")
    end

    vim.g.colors_name = "gruvbox"
    vim.o.termguicolors = true

    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end

colorscheme()
