keymap:
  - name: Sioyek Escape
    application:
      only: sioyek
    exact_match: true
    remap:
      C-c: Esc
  - name: Swayimg hold to close
    application:
      only: swayimg
    exact_match: true
    remap:
      q: F19
