#:schema https://yazi-rs.github.io/schemas/theme.json
# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark  = ""
light = ""

# : }}}


# : App {{{

[app]
overall = {}

# : }}}


# : Manager {{{

[mgr]
# cwd = {}

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { italic = true, fg = "green" }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }
marker_symbol   = "│"

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "black", bg = "yellow" }

# Border
border_style  = {
    hidden = true
}

# Highlighting
syntect_theme = "~/.config/bat/themes/gruvbox-modified.tmTheme"

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "green", bold = false }
inactive = { fg = "#7c6f64"  }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { bg = "#7daea3", fg = "black"}
normal_alt  = { fg = "blue", bg = "gray" }

# Select mode
select_main = { bg = "red", bold = true }
select_alt  = { fg = "red", bg = "gray" }

# Unset mode
unset_main = { bg = "red", bold = true }
unset_alt  = { fg = "red", bg = "gray" }

# : }}}


# : Indicator of hovered file {{{

[indicator]
# parent  = {reversed=true}
# current = {reversed=true}
preview = {reversed=true}
padding = { open = "█", close = "█" }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "white" }
perm_type  = { fg = "lightblue" }
perm_read  = { fg = "lightyellow" }
perm_write = { fg = "lightred" }
perm_exec  = { fg = "lightcyan" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "green", bg = "black" }
progress_error  = { fg = "yellow", bg = "red" }

# : }}}


# : Which {{{

[which]
border          = { fg = "blue" }
cols            = 3
mask            = {}
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "blue" }
title      = { fg = "blue" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [y]es  ", "  (n)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "blue" }
title  = { fg = "blue" }

# Table
tbl_col  = { fg = "blue" }
tbl_cell = { fg = "yellow", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", bold = true }

# : }}}


# : Help menu {{{

[help]
border  = { fg = "blue" }
chord   = { fg = "cyan" }
action  = {}
hovered = { reversed = true, bold = true }

# : }}}


# : File-specific styles {{{

[filetype]
rules = [
#shell
    {mime = "text/shellscript", fg = "green", bold = true},
	# Image
	{ mime = "**/image/*", fg = "yellow" },
	# Media
	{ mime = "**/{audio,video}/*", fg = "magenta" },
	# Archive
	{ mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },
	# Document
	{ mime = "**/application/{pdf,doc,rtf}", fg = "lightblue" },
	{ url = "*.md", fg = "lightblue" },
	{ url = "*.txt", fg = "lightblue" },
	{ url = "*.go", fg = "cyan"  },
	{ url = "*.py", fg = "lightblue" },
	{ url = "*.lua", fg = "yellow" },
	# Virtual file system
	{ url = "*/", is = "link", fg = "cyan", bold = true },
	{ mime = "vfs/{absent,stale}", fg = "gray" },
	# Special file
	{ url = "*", is = "orphan", bg = "red" },
	{ url = "*", is = "exec"  , fg = "green" },
	# Dummy file
	{ url = "*", is = "dummy", bg = "red" },
	{ url = "*/", is = "dummy", bg = "red" },
    #custom dirs
	{ url = "/home/", fg ="yellow", reversed = true },
	{ url = "*araaha/", fg ="yellow", reversed = true },
	{ url = "*dotfiles-private/", fg ="yellow" },
	{ url = "*Screenshots/", fg ="white", bold = true, reversed=false },
	{ url = "*Downloads/", fg ="magenta", bold = true, reversed=false },
	{ url = "*.config/", fg ="green", bold = true  },
	{ url = "*dotfiles/", fg ="yellow", bold = false },
	{ url = "*share/", fg ="white", dim =true, bold = true },
	{ url = "/usr/", fg ="blue", bold = true, dim  = true },
	{ url = "/etc/", fg ="red", bold = true , dim  = true},
	{ url = "/tmp/", fg ="magenta", bold = true , dim  = true},
	# Fallback
	{ url = "*/", fg = "blue", bold = true }
]

# : }}}


# : Icons {{{

[icon]
dirs = []
files = [
  { name = "configure", text = "" },
  { name = "dockerfile", text = "" },
  { name = "Dockerfile", text = "" },
  { name = "dropbox", text = "" },
  { name = "gemfile", text = "" },
  { name = "ledger", text = "" },
  { name = "license", text = "" },
  { name = "LICENSE", text = "" },
  { name = "LICENSE.md", text = "" },
  { name = "makefile", text = "" },
  { name = "Makefile", text = "" },
  { name = "package.json", text = "" },
  { name = "playlists", text = "" },
  { name = "procfile", text = "" },
  { name = "rakefile", text = "" },
  { name = "Rakefile", text = "" },
  { name = "react.jsx", text = "" },
  { name = "README", text = "" },
  { name = "README.md", text = "" },
]
exts = [
  { name = "7z", text = "" },
  { name = "a", text = "" },
  { name = "aac", text = "" },
  { name = "ace", text = "" },
  { name = "ai", text = "" },
  { name = "alz", text = "" },
  { name = "apk", text = "" },
  { name = "arc", text = "" },
  { name = "arj", text = "" },
  { name = "asf", text = "" },
  { name = "asm", text = "" },
  { name = "asp", text = "" },
  { name = "au", text = "" },
  { name = "aup", text = "" },
  { name = "avi", text = "" },
  { name = "awk", text = "" },
  { name = "bash", text = "" },
  { name = "bash_aliases", text = "" },
  { name = "bash_history", text = "" },
  { name = "bash_logout", text = "" },
  { name = "bash_profile", text = "" },
  { name = "bashprofile", text = "" },
  { name = "bashrc", text = "" },
  { name = "bat", text = "" },
  { name = "bmp", text = "" },
  { name = "bz", text = "" },
  { name = "bz2", text = "" },
  { name = "c++", text = "" },
  { name = "c", text = "" },
  { name = "cab", text = "" },
  { name = "cbr", text = "" },
  { name = "cbz", text = "" },
  { name = "cc", text = "" },
  { name = "cgm", text = "" },
  { name = "class", text = "" },
  { name = "clj", text = "" },
  { name = "cljc", text = "" },
  { name = "cljs", text = "" },
  { name = "cmake", text = "" },
  { name = "cmd", text = "" },
  { name = "coffee", text = "" },
  { name = "conf", text = "" },
  { name = "cp", text = "" },
  { name = "cpio", text = "" },
  { name = "cpp", text = "" },
  { name = "cs", text = "" },
  { name = "csh", text = "" },
  { name = "css", text = "" },
  { name = "cue", text = "" },
  { name = "cvs", text = "" },
  { name = "cxx", text = "" },
  { name = "d", text = "" },
  { name = "dart", text = "" },
  { name = "db", text = "" },
  { name = "deb", text = "" },
  { name = "diff", text = "" },
  { name = "djvu", text = "龎" },
  { name = "dl", text = "" },
  { name = "dll", text = "" },
  { name = "dmrc", text = "" },
  { name = "doc", text = "" },
  { name = "docx", text = "" },
  { name = "dump", text = "" },
  { name = "dwm", text = "" },
  { name = "dz", text = "" },
  { name = "ear", text = "" },
  { name = "edn", text = "" },
  { name = "eex", text = "" },
  { name = "efi", text = "" },
  { name = "ejs", text = "" },
  { name = "elf", text = "" },
  { name = "elm", text = "" },
  { name = "emf", text = "" },
  { name = "epub", text = "" },
  { name = "erl", text = "" },
  { name = "esd", text = "" },
  { name = "ex", text = "" },
  { name = "exe", text = "" },
  { name = "exs", text = "" },
  { name = "f#", text = "" },
  { name = "fasd", text = "" },
  { name = "fehbg", text = "" },
  { name = "fish", text = "" },
  { name = "fifo", text = "ﳣ" },
  { name = "flac", text = "" },
  { name = "flc", text = "" },
  { name = "fli", text = "" },
  { name = "flv", text = "" },
  { name = "fs", text = "" },
  { name = "fsi", text = "" },
  { name = "fsscript", text = "" },
  { name = "fsx", text = "" },
  { name = "gem", text = "" },
  { name = "gemspec", text = "" },
  { name = "gif", text = "" },
  { name = "gitattributes", text = "" },
  { name = "gitconfig", text = "" },
  { name = "gitignore", text = "" },
  { name = "gl", text = "" },
  { name = "go", text = "" },
  { name = "gvimrc", text = "" },
  { name = "gz", text = "" },
  { name = "gzip", text = "" },
  { name = "h", text = "" },
  { name = "haml", text = "" },
  { name = "hbs", text = "" },
  { name = "hh", text = "" },
  { name = "hpp", text = "" },
  { name = "hrl", text = "" },
  { name = "hs", text = "" },
  { name = "htaccess", text = "" },
  { name = "htm", text = "" },
  { name = "html", text = "" },
  { name = "htpasswd", text = "" },
  { name = "hxx", text = "" },
  { name = "ico", text = "" },
  { name = "img", text = "" },
  { name = "ini", text = "" },
  { name = "inputrc", text = "" },
  { name = "iso", text = "" },
  { name = "jar", text = "" },
  { name = "java", text = "" },
  { name = "jl", text = "" },
  { name = "jpeg", text = "" },
  { name = "jpg", text = "" },
  { name = "js", text = "" },
  { name = "json", text = "" },
  { name = "jsx", text = "" },
  { name = "key", text = "" },
  { name = "ksh", text = "" },
  { name = "leex", text = "" },
  { name = "less", text = "" },
  { name = "lha", text = "" },
  { name = "lhs", text = "" },
  { name = "log", text = "" },
  { name = "lrz", text = "" },
  { name = "lua", text = "" },
  { name = "lz", text = "" },
  { name = "lz4", text = "" },
  { name = "lzh", text = "" },
  { name = "lzma", text = "" },
  { name = "lzo", text = "" },
  { name = "m2v", text = "" },
  { name = "m4a", text = "" },
  { name = "m4v", text = "" },
  { name = "markdown", text = "" },
  { name = "md", text = "" },
  { name = "mdx", text = "" },
  { name = "mid", text = "" },
  { name = "midi", text = "" },
  { name = "mjpeg", text = "" },
  { name = "mjpg", text = "" },
  { name = "mjs", text = "" },
  { name = "mka", text = "" },
  { name = "mkv", text = "" },
  { name = "mli", text = "λ" },
  { name = "ml", text = "λ" },
  { name = "mng", text = "" },
  { name = "mov", text = "" },
  { name = "mp3", text = "" },
  { name = "mp4", text = "" },
  { name = "mp4v", text = "" },
  { name = "mpc", text = "" },
  { name = "mpeg", text = "" },
  { name = "mpg", text = "" },
  { name = "msi", text = "" },
  { name = "mustache", text = "" },
  { name = "ncmpcpp", text = "" },
  { name = "nix", text = "" },
  { name = "nuv", text = "" },
  { name = "nvidia-settings-rc", text = "" },
  { name = "o", text = "" },
  { name = "oga", text = "" },
  { name = "ogg", text = "" },
  { name = "ogm", text = "" },
  { name = "ogv", text = "" },
  { name = "ogx", text = "" },
  { name = "opus", text = "" },
  { name = "pam_environment", text = "" },
  { name = "part", text = "" },
  { name = "pbm", text = "" },
  { name = "pcx", text = "" },
  { name = "pdf", text = "" },
  { name = "pgm", text = "" },
  { name = "php", text = "" },
  { name = "pl", text = "" },
  { name = "pm", text = "" },
  { name = "png", text = "" },
  { name = "pp", text = "" },
  { name = "ppm", text = "" },
  { name = "ppt", text = "" },
  { name = "pptx", text = "" },
  { name = "pro", text = "" },
  { name = "profile", text = "" },
  { name = "ps1", text = "" },
  { name = "psb", text = "" },
  { name = "psd", text = "" },
  { name = "pub", text = "" },
  { name = "py", text = "" },
  { name = "pyc", text = "" },
  { name = "pyd", text = "" },
  { name = "pyo", text = "" },
  { name = "qt", text = "" },
  { name = "ra", text = "" },
  { name = "rake", text = "" },
  { name = "rar", text = "" },
  { name = "rb", text = "" },
  { name = "rc", text = "" },
  { name = "rlib", text = "" },
  { name = "rm", text = "" },
  { name = "rmd", text = "" },
  { name = "rmvb", text = "" },
  { name = "rom", text = "" },
  { name = "rpm", text = "" },
  { name = "rproj", text = "鉶" },
  { name = "rs", text = "" },
  { name = "rss", text = "" },
  { name = "rtf", text = "" },
  { name = "rz", text = "" },
  { name = "r", text = "ﳒ" },
  { name = "s", text = "" },
  { name = "sar", text = "" },
  { name = "sass", text = "" },
  { name = "scala", text = "" },
  { name = "scss", text = "" },
  { name = "sh", text = "" },
  { name = "slim", text = "" },
  { name = "sln", text = "" },
  { name = "so", text = "" },
  { name = "spx", text = "" },
  { name = "sql", text = "" },
  { name = "styl", text = "" },
  { name = "suo", text = "" },
  { name = "svg", text = "" },
  { name = "svgz", text = "" },
  { name = "swift", text = "" },
  { name = "swm", text = "" },
  { name = "t", text = "" },
  { name = "t7z", text = "" },
  { name = "tar", text = "" },
  { name = "taz", text = "" },
  { name = "tbz", text = "" },
  { name = "tbz2", text = "" },
  { name = "tex", text = "ﭨ" },
  { name = "tga", text = "" },
  { name = "tgz", text = "" },
  { name = "tif", text = "" },
  { name = "tiff", text = "" },
  { name = "tlz", text = "" },
  { name = "toml", text = "" },
  { name = "torrent", text = "" },
  { name = "ts", text = "" },
  { name = "tsx", text = "" },
  { name = "twig", text = "" },
  { name = "txz", text = "" },
  { name = "typ", text = "ﭨ" },
  { name = "tz", text = "" },
  { name = "tzo", text = "" },
  { name = "tzst", text = "" },
  { name = "vim", text = "" },
  { name = "vimrc", text = "" },
  { name = "vob", text = "" },
  { name = "vue", text = "﵂" },
  { name = "war", text = "" },
  { name = "wav", text = "" },
  { name = "webm", text = "" },
  { name = "webmanifest", text = "" },
  { name = "webp", text = "" },
  { name = "wim", text = "" },
  { name = "wmv", text = "" },
  { name = "Xauthority", text = "" },
  { name = "xbm", text = "" },
  { name = "xbps", text = "" },
  { name = "xcf", text = "" },
  { name = "xcplayground", text = "" },
  { name = "Xdefaults", text = "" },
  { name = "xhtml", text = "" },
  { name = "xinitrc", text = "" },
  { name = "xinputrc", text = "" },
  { name = "xls", text = "" },
  { name = "xlsx", text = "" },
  { name = "xml", text = "" },
  { name = "xpm", text = "" },
  { name = "Xresources", text = "" },
  { name = "xspf", text = "" },
  { name = "xul", text = "" },
  { name = "xwd", text = "" },
  { name = "xz", text = "" },
  { name = "yaml", text = "" },
  { name = "yml", text = "" },
  { name = "yuv", text = "" },
  { name = "z", text = "" },
  { name = "zip", text = "" },
  { name = "zoo", text = "" },
  { name = "zsh", text = "" },
  { name = "zshrc", text = "" },
  { name = "zst", text = "" },
]
conds = [
  { if = "link", text = "" },
  { if = "dir", text = "" },
  { if = "exec", text = "" },
  { if = "!dir", text = "" },
]
# : }}}
