alias \#='sudo'
alias \$=''
alias bdisc="bluetoothctl disconnect 18:9C:2C:4F:BB:5F"
alias bconn="bluetoothctl connect 18:9C:2C:4F:BB:5F"
alias cat="bat -pp --color=auto"
alias catt="/usr/bin/cat"
alias copy="xclip -r -sel clip"
alias cp='cp -v'
alias cyme="sudo cyme --hide-buses -b icon -b name -b speed -t"
alias farge="farge --image-viewer nsxiv"
alias ga="git add"
alias gc="git commit"
alias gdu="gdu -c"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gp="git push"
alias grep="grep --color=always"
alias gs="git status"
alias lf="TERM=xterm-256color l-ueberzug"
alias lg="lazygit"
alias ls="ls --color=always"
alias lsusb="sudo cyme --hide-buses -b icon -b name -b speed -t"
alias mega-cmd="env HOME=/home/araaha/.local/share/ mega-cmd"
alias ncdu="gdu -c"
alias nerdfetch="nitch -a"
alias nsxiv="nsxiv -g 800x600+560+240 -b -a -sf"
alias nv="nvim"
alias packages="ls -lt /var/lib/pacman/local/ --color=never | head -n 30 | tail -n +2 | tac | awk '{ print \$9}'"
alias ticker='ticker --sort=user --config="$HOME/.config/.ticker.yaml"'
alias tree="tree --noreport -C"
alias ssh='ssh -F "$SSH_HOME"/config -o UserKnownHostsFile="$SSH_HOME"/known_hosts'
